 tic
        tface2index=find(t1(4,:)==2);
        pface2index=t1(1:3,tface2index);
        pface2index=unique(pface2index);
        pface2coord=[p1(:,pface2index);pface2index';zeros(1,size(pface2index,1))];
        pface2coord=sortrows(pface2coord',1);
        pface2coord(1:end/2,:)=sortrows(pface2coord(1:end/2,:),2);
        pface2coord(end/2+1:end,:)=sortrows(pface2coord(end/2+1:end,:),2);     
        pface2coord(1:end/2,4)=faultslip(1:size(pface2coord,1)/2)';
        pface2coord(end/2+1:end,4)=faultslip(1:size(pface2coord,1)/2)';
        Trise=zeros(1,size(p1,2));
        Trise(pface2coord(:,3))=(0.6*9.8.*pface2coord(:,2).*abs(pface2coord(:,4)))/(ther.cp*faultwidth);
        Tfield=Tfield+Trise;
        toc